# Generated by Django 5.2 on 2025-04-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
